webtalk_init -webtalk_dir /run/media/ondra/enc/Sync/BPC-EKT2L/BPC-DE1/cviceni/Digital-electronics-1/Labs/06-display_driver/display_driver/display_driver.sim/sim_1/behav/xsim/xsim.dir/tb_driver_7seg_4digits_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Mar 21 17:25:24 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "b78ef367-aea0-4644-b6f8-8c12fa53105e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "5dcfb3219f5d440bb25f4e1529e59e2c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "34" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "openSUSE" -context "user_environment"
webtalk_add_data -client project -key os_release -value "openSUSE Tumbleweed" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD A10-7870K Radeon R7, 12 Compute Cores 4C+8G" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2400.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "20.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.29_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "115164_KB" -context "xsim\\usage"
webtalk_transmit -clientid 112646136 -regid "" -xml /run/media/ondra/enc/Sync/BPC-EKT2L/BPC-DE1/cviceni/Digital-electronics-1/Labs/06-display_driver/display_driver/display_driver.sim/sim_1/behav/xsim/xsim.dir/tb_driver_7seg_4digits_behav/webtalk/usage_statistics_ext_xsim.xml -html /run/media/ondra/enc/Sync/BPC-EKT2L/BPC-DE1/cviceni/Digital-electronics-1/Labs/06-display_driver/display_driver/display_driver.sim/sim_1/behav/xsim/xsim.dir/tb_driver_7seg_4digits_behav/webtalk/usage_statistics_ext_xsim.html -wdm /run/media/ondra/enc/Sync/BPC-EKT2L/BPC-DE1/cviceni/Digital-electronics-1/Labs/06-display_driver/display_driver/display_driver.sim/sim_1/behav/xsim/xsim.dir/tb_driver_7seg_4digits_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
