#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Mar 01 21:36:18 CET 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 1f93df37be124118a145c0ae4c98c024 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_mux_2bit_4to1_behav xil_defaultlib.tb_mux_2bit_4to1 -log elaborate.log"
xelab -wto 1f93df37be124118a145c0ae4c98c024 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_mux_2bit_4to1_behav xil_defaultlib.tb_mux_2bit_4to1 -log elaborate.log

